### ISSUE TITLE
No need for if (xhr.readyState === 4)

### ISSUE THREAD

**Issue by tkrotoff** [pizzapanther/Karma-Read-JSON#2]
https://github.com/pizzapanther/Karma-Read-JSON/blob/v1.0.2/karma-read-json.js#L10

``` JavaScript
xhr.onload = function() {
  if (xhr.readyState === 4) { // <== Not needed with onload, only with onreadystatechange
  }
};
```

onload is "invoked when the operation is successfully completed", see https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequestEventTarget
And xhr.readyState === 4 means "The operation is complete", see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

See also http://www.html5rocks.com/en/tutorials/file/xhr2/

**Comment by pizzapanther** [comment]
Fixed: https://github.com/pizzapanther/Karma-Read-JSON/commit/98d94106a16ad7ef322a220c33074cdc94ca4689
